/* prettier-ignore */
// This file is auto-generated by @tanstack/router-plugin on every build/dev start.
// Do not edit manually — changes will be overwritten.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as RootImport } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as NotesImport } from './routes/notes'
import { Route as RoomsRoomIdImport } from './routes/rooms.$roomId'
import { Route as ApiProxySplatImport } from './routes/api/proxy.$'

const RootRoute = RootImport
const IndexRoute = IndexImport.update({ path: '/', getParentRoute: () => RootRoute } as any)
const NotesRoute = NotesImport.update({ path: '/notes', getParentRoute: () => RootRoute } as any)
const RoomsRoomIdRoute = RoomsRoomIdImport.update({ path: '/rooms/$roomId', getParentRoute: () => RootRoute } as any)
const ApiProxySplatRoute = ApiProxySplatImport.update({ path: '/api/proxy/$', getParentRoute: () => RootRoute } as any)

export interface FileRoutesByPath {
  '/': { preLoaderRoute: typeof IndexImport; parentRoute: typeof RootRoute }
  '/notes': { preLoaderRoute: typeof NotesImport; parentRoute: typeof RootRoute }
  '/rooms/$roomId': { preLoaderRoute: typeof RoomsRoomIdImport; parentRoute: typeof RootRoute }
  '/api/proxy/$': { preLoaderRoute: typeof ApiProxySplatImport; parentRoute: typeof RootRoute }
}

export const routeTree = RootRoute.addChildren([
  IndexRoute,
  NotesRoute,
  RoomsRoomIdRoute,
  ApiProxySplatRoute,
])
